# Generated by Django 4.2 on 2025-10-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Film nomi')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('year', models.IntegerField(verbose_name='Yil')),
                ('genre', models.CharField(max_length=100, verbose_name='Janr')),
                ('director', models.CharField(max_length=100, verbose_name='Rejissyor')),
                ('actors', models.CharField(blank=True, max_length=200, verbose_name='Aktyorlar')),
                ('duration', models.CharField(max_length=50, verbose_name='Davomiyligi')),
                ('rating', models.FloatField(default=0.0, verbose_name='Reyting')),
                ('poster_file', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Poster rasm (yuklash)')),
                ('poster_url', models.URLField(blank=True, verbose_name='Poster URL (link)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video fayl (yuklash)')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL (link)')),
                ('trailer_url', models.URLField(blank=True, verbose_name='Treyler URL')),
                ('is_featured', models.BooleanField(default=False, verbose_name="Bosh sahifada ko'rsatish")),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filmlar',
                'ordering': ['-year', 'title'],
            },
        ),
    ]
