# Generated by Django 4.2 on 2025-10-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemadia', '0002_alter_movie_options_movie_created_at_and_more'),
    ]

    operations = [
    ]
