# Generated by Django 4.2 on 2025-10-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemadia', '0003_set_created_at_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('serial', 'Serial'), ('tarjima_kino', 'Tarjima Kino'), ('premyera', 'Premyera'), ('klassika', 'Klassika'), ('yangilik', 'Yangilik'), ('eng_yaxshi', 'Eng Yaxshi')], default='yangilik', max_length=20, verbose_name='Kategoriya'),
        ),
    ]
