# Generated by Django 4.2 on 2025-10-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemadia', '0004_movie_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='content_type',
            field=models.CharField(choices=[('tarjima_kino', 'Tarjima Kino'), ('premyera', 'Premyera'), ('hind_kino', 'Hind Kino'), ('multifilm', 'Multifilm')], default='tarjima_kino', max_length=20, verbose_name='Kino turi'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_serial',
            field=models.BooleanField(default=False, verbose_name='Serial'),
        ),
    ]
