# Generated by Django 4.2 on 2025-10-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemadia', '0005_remove_movie_category_movie_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_serial',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('serial', 'Serial'), ('tarjima_kino', 'Tarjima Kino'), ('premyera', 'Premyera'), ('klassika', 'Klassika'), ('yangilik', 'Yangilik'), ('eng_yaxshi', 'Eng Yaxshi'), ('jangari', 'Jangari'), ('komediya', 'Komediya'), ('drama', 'Drama'), ('romantik', 'Romantik'), ('qorqinchli', 'Qorqinchli'), ('fantastik', 'Fantastik'), ('tarixiy', 'Tarixiy')], default='yangilik', max_length=20, verbose_name='Kategoriya'),
        ),
    ]
