# Generated by Django 4.2 on 2025-10-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemadia', '0006_remove_movie_content_type_remove_movie_is_serial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
    ]
