# Generated by Django 4.2 on 2025-10-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemadia', '0008_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('serial', 'Serial'), ('tarjima_kino', 'Tarjima Kino'), ('premyera', 'Premyera'), ('hind', 'Hind Kinolari'), ('multfilm', 'Multfilmlar'), ('klassika', 'Klassika'), ('yangilik', 'Yangilik'), ('eng_yaxshi', 'Eng Yaxshi')], default='yangilik', max_length=20, verbose_name='Kategoriya'),
        ),
    ]
