# Generated by Django 4.2 on 2025-10-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemadia', '0010_alter_movie_options_alter_movie_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('serial', 'Serial'), ('tarjima_kino', 'Tarjima kinolar'), ('premyera', 'Premyera'), ('hind', 'Hind kinolari'), ('multfilm', 'Multfilmlar'), ('klassika', 'Klassika'), ('yangilik', 'Yangilik'), ('eng_yaxshi', 'Eng Yaxshi'), ('jangari', 'Jangari'), ('drama', 'Drama'), ('komediya', 'Komediya'), ('melodrama', 'Melodrama'), ('sarguzasht', 'Sarguzasht'), ('qorquv', "Qo'rqinchli"), ('tarixiy', 'Tarixiy'), ('fantastika', 'Fantastika'), ('hayotiy', 'Hayotiy'), ('triller', 'Triller'), ('detektiv', 'Detektiv'), ('hujjatli', 'Hujjatli'), ('anime', 'Anime'), ('kriminal', 'Kriminal'), ('fentezi', 'Fentezi'), ('afsona', 'Afsona'), ('vester', 'Vester'), ('musiqiy', 'Musiqiy'), ('romantik', 'Romantik'), ('oilaviy', 'Oilaviy'), ('jangovar', 'Jangovar'), ('mistik', 'Mistik'), ('ilmiy', 'Ilmiy'), ('sport', 'Sport')], default='yangilik', max_length=20, verbose_name='Kategoriya'),
        ),
    ]
