from django.core.management.base import BaseCommand
from cinemadia.models import Movie
import random

class Command(BaseCommand):
    help = 'Add real movies to the database'

    def handle(self, *args, **kwargs):
        # Remove existing sample movies
        Movie.objects.filter(title__startswith='Movie').delete()
        Movie.objects.filter(title__startswith='Extra Movie').delete()
        
        # Real movie data
        real_movies_data = [
            {
                'title': 'Inception',
                'description': 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
                'year': 2010,
                'genre': 'Action, Adventure, Sci-Fi',
                'director': 'Christopher Nolan',
                'actors': 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page',
                'duration': '2h 28m',
                'rating': 8.8,
                'poster_url': 'https://image.tmdb.org/t/p/w500/qmDpIHrmpJINaRKAfWQfftjCdyi.jpg',
                'trailer_url': 'https://www.youtube.com/watch?v=YoHD9XEInc0',
                'is_featured': True,
                'category': 'fantastika',
            },
            {
                'title': 'The Dark Knight',
                'description': 'When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.',
                'year': 2008,
                'genre': 'Action, Crime, Drama',
                'director': 'Christopher Nolan',
                'actors': 'Christian Bale, Heath Ledger, Aaron Eckhart',
                'duration': '2h 32m',
                'rating': 9.0,
                'poster_url': 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
                'trailer_url': 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
                'is_featured': True,
                'category': 'jangari',
            },
            {
                'title': 'The Crown',
                'description': 'Follows the political rivalries and romance of Queen Elizabeth II’s reign and the events that shaped the 20th century.',
                'year': 2016,
                'genre': 'Drama, History, Biography',
                'director': 'Peter Morgan',
                'actors': 'Claire Foy, Olivia Colman, Matt Smith',
                'duration': '58m per episode',
                'rating': 8.7,
                'poster_url': 'https://image.tmdb.org/t/p/w500/vEYAuGUt64QbQWizVEz8cachAk6.jpg',
                'trailer_url': 'https://www.youtube.com/watch?v=JWtnJjn6ng0',
                'is_featured': True,
                'category': 'serial',
            },
            {
        "title": "The Crown",
        "description": "Follows the political rivalries and romance of Queen Elizabeth II’s reign and the events that shaped the 20th century.",
        "year": 2016,
        "genre": "Drama, History, Biography",
        "director": "Peter Morgan",
        "actors": "Claire Foy, Olivia Colman, Matt Smith",
        "duration": "58m per episode",
        "rating": 8.7,
        "poster_url": "https://image.tmdb.org/t/p/w500/vEYAuGUt64QbQWizVEz8cachAk6.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=JWtnJjn6ng0",
        "is_featured": True,
        "category": "serial"
      },
      {
        "title": "Breaking Bad",
        "description": "A chemistry teacher turns to cooking meth to secure his family's future after a cancer diagnosis.",
        "year": 2008,
        "genre": "Crime, Drama, Thriller",
        "director": "Vince Gilligan",
        "actors": "Bryan Cranston, Aaron Paul, Anna Gunn",
        "duration": "49m per episode",
        "rating": 9.5,
        "poster_url": "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfO2RHtC4.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=HhesaQXLuRY",
        "is_featured": True,
        "category": "serial"
      },
      {
        "title": "Game of Thrones",
        "description": "Noble families vie for the Iron Throne while an ancient evil threatens the realm.",
        "year": 2011,
        "genre": "Action, Adventure, Drama",
        "director": "David Benioff, D.B. Weiss",
        "actors": "Emilia Clarke, Kit Harington, Peter Dinklage",
        "duration": "1h per episode",
        "rating": 9.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01s9hrUnQ.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=giYeaQsXRYg",
        "is_featured": True,
        "category": "serial"
      },
      {
        "title": "The Sopranos",
        "description": "A New Jersey mob boss balances crime family duties with therapy for panic attacks.",
        "year": 1999,
        "genre": "Crime, Drama",
        "director": "David Chase",
        "actors": "James Gandolfini, Lorraine Bracco, Edie Falco",
        "duration": "55m per episode",
        "rating": 9.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/pw2m3B9.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=dHa95iyg4.jpg",
        "is_featured": False,
        "category": "serial"
      },
      {
        "title": "The Wire",
        "description": "Baltimore's drug trade, police, and institutions are dissected across multiple seasons.",
        "year": 2002,
        "genre": "Crime, Drama",
        "director": "David Simon",
        "actors": "Dominic West, Lance Reddick, Sonja Sohn",
        "duration": "1h per episode",
        "rating": 9.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/4v2n.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=ZH5i.jpg",
        "is_featured": True,
        "category": "serial"
      },
      {
        "title": "Mad Men",
        "description": "A 1960s ad man's life unravels amid cultural shifts and personal secrets.",
        "year": 2007,
        "genre": "Drama",
        "director": "Matthew Weiner",
        "actors": "Jon Hamm, Elisabeth Moss, Vincent Kartheiser",
        "duration": "47m per episode",
        "rating": 8.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/eW8k.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=W6D2.jpg",
        "is_featured": True,
        "category": "serial"
      },
      {
        "title": "Succession",
        "description": "A dysfunctional media dynasty battles for control of their empire amid betrayal and intrigue.",
        "year": 2018,
        "genre": "Drama",
        "director": "Jesse Armstrong",
        "actors": "Brian Cox, Jeremy Strong, Sarah Snook",
        "duration": "1h per episode",
        "rating": 8.8,
        "poster_url": "https://image.tmdb.org/t/p/w500/lz66.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=OzYxJV.jpg",
        "is_featured": True,
        "category": "serial"
      },
      {
        "title": "Stranger Things",
        "description": "Kids in the 1980s uncover supernatural mysteries and government conspiracies in their small town.",
        "year": 2016,
        "genre": "Drama, Fantasy, Horror",
        "director": "The Duffer Brothers",
        "actors": "Winona Ryder, David Harbour, Finn Wolfhard",
        "duration": "50m per episode",
        "rating": 8.7,
        "poster_url": "https://image.tmdb.org/t/p/w500/x2LS.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=XWxy6.jpg",
        "is_featured": True,
        "category": "serial"
      },
      {
        "title": "Westworld",
        "description": "A futuristic theme park with sentient robots spirals into chaos as machines gain self-awareness.",
        "year": 2016,
        "genre": "Drama, Mystery, Sci-Fi",
        "director": "Jonathan Nolan, Lisa Joy",
        "actors": "Evan Rachel Wood, Thandiwe Newton, Jeffrey Wright",
        "duration": "1h per episode",
        "rating": 8.5,
        "poster_url": "https://image.tmdb.org/t/p/w500/y3B.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=9BqKi.jpg",
        "is_featured": True,
        "category": "serial"
      },
      {
        "title": "The Mandalorian",
        "description": "A lone bounty hunter navigates the galaxy, protecting a mysterious baby from dark forces.",
        "year": 2019,
        "genre": "Action, Adventure, Sci-Fi",
        "director": "Jon Favreau",
        "actors": "Pedro Pascal, Gina Carano, Giancarlo Esposito",
        "duration": "40m per episode",
        "rating": 8.7,
        "poster_url": "https://image.tmdb.org/t/p/w500/sWg.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=aOC8E.jpg",
        "is_featured": True,
        "category": "serial"
      },
      {
        "title": "Fargo",
        "description": "Darkly comedic tales of crime and deception unfold in the Midwest, inspired by the Coen Brothers' film.",
        "year": 2014,
        "genre": "Crime, Drama, Thriller",
        "director": "Noah Hawley",
        "actors": "Billy Bob Thornton, Martin Freeman, Allison Tolman",
        "duration": "53m per episode",
        "rating": 8.9,
        "poster_url": "https://image.tmdb.org/t/p/w500/9z2.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=2pV7.jpg",
        "is_featured": False,
        "category": "serial"
      },
      {
        "title": "True Detective",
        "description": "An anthology of dark, complex crime stories with detectives facing personal and professional demons.",
        "year": 2014,
        "genre": "Crime, Drama, Mystery",
        "director": "Nic Pizzolatto",
        "actors": "Matthew McConaughey, Woody Harrelson, Colin Farrell",
        "duration": "55m per episode",
        "rating": 8.9,
        "poster_url": "https://image.tmdb.org/t/p/w500/cW7.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=TXwB.jpg",
        "is_featured": True,
        "category": "serial"
      },
      {
        "title": "Better Call Saul",
        "description": "A small-time lawyer's journey into the criminal underworld, a prequel to Breaking Bad.",
        "year": 2015,
        "genre": "Crime, Drama",
        "director": "Vince Gilligan, Peter Gould",
        "actors": "Bob Odenkirk, Jonathan Banks, Rhea Seehorn",
        "duration": "46m per episode",
        "rating": 8.8,
        "poster_url": "https://image.tmdb.org/t/p/w500/fW6.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=HN4o.jpg",
        "is_featured": True,
        "category": "serial"
      },
      {
        "title": "Black Mirror",
        "description": "An anthology series exploring dark futures shaped by technology and human nature.",
        "year": 2011,
        "genre": "Drama, Sci-Fi, Thriller",
        "director": "Charlie Brooker",
        "actors": "Daniel Kaluuya, Bryce Dallas Howard, Jesse Plemons",
        "duration": "1h per episode",
        "rating": 8.8,
        "poster_url": "https://image.tmdb.org/t/p/w500/pW6.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=jDiY.jpg",
        "is_featured": True,
        "category": "serial"
      },
      {
        "title": "Chernobyl",
        "description": "The devastating 1986 nuclear disaster and the heroic efforts to contain its fallout.",
        "year": 2019,
        "genre": "Drama, History, Thriller",
        "director": "Craig Mazin",
        "actors": "Jared Harris, Stellan Skarsgård, Emily Watson",
        "duration": "1h per episode",
        "rating": 9.4,
        "poster_url": "https://image.tmdb.org/t/p/w500/hlW.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=s9AP.jpg",
        "is_featured": True,
        "category": "serial"
      },
      {
        "title": "The Office (US)",
        "description": "A mockumentary on the daily lives of quirky employees at a paper company in Scranton.",
        "year": 2005,
        "genre": "Comedy",
        "director": "Greg Daniels",
        "actors": "Steve Carell, John Krasinski, Rainn Wilson",
        "duration": "22m per episode",
        "rating": 8.9,
        "poster_url": "https://image.tmdb.org/t/p/w500/qWn.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=LHOt.jpg",
        "is_featured": False,
        "category": "serial"
      },
      {
        "title": "Friends",
        "description": "Six friends navigate life, love, and careers in New York City with humor and heart.",
        "year": 1994,
        "genre": "Comedy, Romance",
        "director": "David Crane, Marta Kauffman",
        "actors": "Jennifer Aniston, Courteney Cox, Lisa Kudrow",
        "duration": "22m per episode",
        "rating": 8.9,
        "poster_url": "https://image.tmdb.org/t/p/w500/f4s.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=SM6h.jpg",
        "is_featured": True,
        "category": "serial"
      },
      {
        "title": "The Witcher",
        "description": "A monster hunter, a sorceress, and a princess are bound by destiny in a war-torn world.",
        "year": 2019,
        "genre": "Action, Adventure, Fantasy",
        "director": "Lauren Schmidt Hissrich",
        "actors": "Henry Cavill, Anya Chalotra, Freya Allan",
        "duration": "1h per episode",
        "rating": 8.1,
        "poster_url": "https://image.tmdb.org/t/p/w500/zrI.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=ndl1.jpg",
        "is_featured": True,
        "category": "serial"
      },
      {
        "title": "Peaky Blinders",
        "description": "A gangster family rises in 1919 Birmingham, navigating crime, power, and betrayal.",
        "year": 2013,
        "genre": "Crime, Drama",
        "director": "Steven Knight",
        "actors": "Cillian Murphy, Paul Anderson, Helen McCrory",
        "duration": "1h per episode",
        "rating": 8.8,
        "poster_url": "https://image.tmdb.org/t/p/w500/vw3.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=oVzV.jpg",
        "is_featured": True,
        "category": "serial"
      },
      {
        "title": "Mindhunter",
        "description": "FBI agents in the 1970s develop criminal profiling by studying serial killers.",
        "year": 2017,
        "genre": "Crime, Drama, Thriller",
        "director": "Joe Penhall",
        "actors": "Jonathan Groff, Holt McCallany, Anna Torv",
        "duration": "1h per episode",
        "rating": 8.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/zbH.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=7gZ.jpg",
        "is_featured": False,
        "category": "serial"
      },
      {
        "title": "Inception",
        "description": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        "year": 2010,
        "genre": "Action, Adventure, Sci-Fi",
        "director": "Christopher Nolan",
        "actors": "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
        "duration": "2h 28m",
        "rating": 8.8,
        "poster_url": "https://image.tmdb.org/t/p/w500/qmDpIHrmpJINaRKAfWQfftjCdyi.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=YoHD9XEInc0",
        "is_featured": True,
        "category": "fantastika"
      },
      {
        "title": "The Matrix",
        "description": "A hacker discovers reality is a simulation controlled by machines and joins a rebellion to free humanity.",
        "year": 1999,
        "genre": "Action, Sci-Fi",
        "director": "Lana Wachowski, Lilly Wachowski",
        "actors": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
        "duration": "2h 16m",
        "rating": 8.7,
        "poster_url": "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5Z.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=m8e-8oLKvP8",
        "is_featured": False,
        "category": "fantastika"
      },
      {
        "title": "Blade Runner",
        "description": "A detective hunts rogue androids in a dystopian future, questioning what it means to be human.",
        "year": 1982,
        "genre": "Sci-Fi, Thriller",
        "director": "Ridley Scott",
        "actors": "Harrison Ford, Sean Young, Rutger Hauer",
        "duration": "1h 57m",
        "rating": 8.1,
        "poster_url": "https://image.tmdb.org/t/p/w500/63N9uy8nd9j7Eog2axS8wxUp7M8.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=eogpIG53Cis",
        "is_featured": False,
        "category": "fantastika"
      },
      {
        "title": "Dune",
        "description": "A young noble navigates betrayal, desert survival, and interstellar politics on a hostile planet.",
        "year": 2021,
        "genre": "Adventure, Sci-Fi",
        "director": "Denis Villeneuve",
        "actors": "Timothée Chalamet, Rebecca Ferguson, Oscar Isaac",
        "duration": "2h 35m",
        "rating": 8.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=n9xhJrPZrk4",
        "is_featured": True,
        "category": "fantastika"
      },
      {
        "title": "Alien",
        "description": "A spaceship crew encounters a deadly extraterrestrial organism that hunts them one by one.",
        "year": 1979,
        "genre": "Horror, Sci-Fi",
        "director": "Ridley Scott",
        "actors": "Sigourney Weaver, Tom Skerritt, John Hurt",
        "duration": "1h 57m",
        "rating": 8.4,
        "poster_url": "https://image.tmdb.org/t/p/w500/vfrQk5IPloBbhv9LDSDSrft3z.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=LjLamj-b0I8",
        "is_featured": False,
        "category": "fantastika"
      },
      {
        "title": "E.T. the Extra-Terrestrial",
        "description": "A boy befriends a stranded alien and helps it return home while evading government capture.",
        "year": 1982,
        "genre": "Family, Sci-Fi",
        "director": "Steven Spielberg",
        "actors": "Henry Thomas, Drew Barrymore, Dee Wallace",
        "duration": "1h 55m",
        "rating": 7.8,
        "poster_url": "https://image.tmdb.org/t/p/w500/pG6kyaW1N3QbntH2P5iUwNQB.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=qYAETtIIClk",
        "is_featured": False,
        "category": "fantastika"
      },
      {
        "title": "Back to the Future",
        "description": "A teen accidentally travels to 1955 and must ensure his parents fall in love to secure his future.",
        "year": 1985,
        "genre": "Adventure, Comedy, Sci-Fi",
        "director": "Robert Zemeckis",
        "actors": "Michael J. Fox, Christopher Lloyd, Lea Thompson",
        "duration": "1h 56m",
        "rating": 8.5,
        "poster_url": "https://image.tmdb.org/t/p/w500/fNOH9fE4DH6kj2mP2pK5A5U6.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=qvsgGtivCgs",
        "is_featured": True,
        "category": "fantastika"
      },
      {
        "title": "The Fifth Element",
        "description": "A cab driver teams with a mysterious woman to save the world from an ancient evil.",
        "year": 1997,
        "genre": "Action, Adventure, Sci-Fi",
        "director": "Luc Besson",
        "actors": "Bruce Willis, Milla Jovovich, Gary Oldman",
        "duration": "2h 6m",
        "rating": 7.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/fPtlCO1yQtnoLHOwKtWz3LsvE.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=fQ9Rq3e1N4U",
        "is_featured": False,
        "category": "fantastika"
      },
      {
        "title": "Guardians of the Galaxy",
        "description": "A ragtag group of misfits bands together to stop a cosmic threat and save the galaxy.",
        "year": 2014,
        "genre": "Action, Adventure, Sci-Fi",
        "director": "James Gunn",
        "actors": "Chris Pratt, Zoe Saldana, Dave Bautista",
        "duration": "2h 1m",
        "rating": 8.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=d96cjJhvlMA",
        "is_featured": True,
        "category": "fantastika"
      },
      {
        "title": "Mad Max: Fury Road",
        "description": "In a post-apocalyptic wasteland, a warrior helps a group of women escape a tyrant's rule.",
        "year": 2015,
        "genre": "Action, Sci-Fi",
        "director": "George Miller",
        "actors": "Tom Hardy, Charlize Theron, Nicholas Hoult",
        "duration": "2h 0m",
        "rating": 8.1,
        "poster_url": "https://image.tmdb.org/t/p/w500/8tZYtuWezvX8.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=hEJnMQG9ev8",
        "is_featured": True,
        "category": "fantastika"
      },
      {
        "title": "Spirited Away",
        "description": "A girl enters a spirit world to save her parents and finds her own strength in a magical bathhouse.",
        "year": 2001,
        "genre": "Animation, Adventure, Fantasy",
        "director": "Hayao Miyazaki",
        "actors": "Rumi Hiiragi, Miyu Irino, Mari Natsuki",
        "duration": "2h 5m",
        "rating": 8.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyv.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=ByXuk9QqQkk",
        "is_featured": False,
        "category": "fantastika"
      },
      {
        "title": "Star Wars: The Empire Strikes Back",
        "description": "Rebels battle the Empire while a young hero trains with a Jedi master and faces betrayal.",
        "year": 1980,
        "genre": "Action, Adventure, Sci-Fi",
        "director": "Irvin Kershner",
        "actors": "Mark Hamill, Harrison Ford, Carrie Fisher",
        "duration": "2h 4m",
        "rating": 8.7,
        "poster_url": "https://image.tmdb.org/t/p/w500/6u1fYtxG5eqj.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=JNwNXF9Y6kY",
        "is_featured": True,
        "category": "fantastika"
      },
      {
        "title": "2001: A Space Odyssey",
        "description": "Humanity's evolution is guided by mysterious monoliths, leading to a psychedelic space journey.",
        "year": 1968,
        "genre": "Adventure, Sci-Fi",
        "director": "Stanley Kubrick",
        "actors": "Keir Dullea, Gary Lockwood, William Sylvester",
        "duration": "2h 29m",
        "rating": 8.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/ve72VxNqjGM.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=oR_e9y-bka0",
        "is_featured": False,
        "category": "fantastika"
      },
      {
        "title": "The Terminator",
        "description": "A cyborg assassin from the future hunts a woman whose son will lead a resistance against machines.",
        "year": 1984,
        "genre": "Action, Sci-Fi",
        "director": "James Cameron",
        "actors": "Arnold Schwarzenegger, Linda Hamilton, Michael Biehn",
        "duration": "1h 47m",
        "rating": 8.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/qz9aG8l3x.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=k64P0kSg.jpg",
        "is_featured": False,
        "category": "fantastika"
      },
      {
        "title": "Arrival",
        "description": "A linguist deciphers alien language to avert global catastrophe, unlocking nonlinear time.",
        "year": 2016,
        "genre": "Drama, Sci-Fi",
        "director": "Denis Villeneuve",
        "actors": "Amy Adams, Jeremy Renner, Forest Whitaker",
        "duration": "1h 56m",
        "rating": 7.9,
        "poster_url": "https://image.tmdb.org/t/p/w500/x2FJ.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=tFMo3.jpg",
        "is_featured": True,
        "category": "fantastika"
      },
      {
        "title": "Jurassic Park",
        "description": "Scientists unleash cloned dinosaurs on a remote island, turning a theme park into chaos.",
        "year": 1993,
        "genre": "Adventure, Sci-Fi",
        "director": "Steven Spielberg",
        "actors": "Sam Neill, Laura Dern, Jeff Goldblum",
        "duration": "2h 7m",
        "rating": 8.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/oU7.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=QWBKx.jpg",
        "is_featured": True,
        "category": "fantastika"
      },
      {
        "title": "Interstellar",
        "description": "Astronauts seek a new home for humanity through a wormhole, facing time and space dilemmas.",
        "year": 2014,
        "genre": "Adventure, Drama, Sci-Fi",
        "director": "Christopher Nolan",
        "actors": "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
        "duration": "2h 49m",
        "rating": 8.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/gEU2.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=zSWdZVt.jpg",
        "is_featured": True,
        "category": "fantastika"
      },
      {
        "title": "Pan's Labyrinth",
        "description": "A girl discovers a mythical labyrinth and tasks from a faun amid Spain's civil war horrors.",
        "year": 2006,
        "genre": "Drama, Fantasy",
        "director": "Guillermo del Toro",
        "actors": "Ivana Baquero, Sergi López, Maribel Verdú",
        "duration": "1h 58m",
        "rating": 8.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/zp6Z.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=EqYi.jpg",
        "is_featured": False,
        "category": "fantastika"
      },
      {
        "title": "Children of Men",
        "description": "In a barren future, a man protects a miraculously pregnant woman from a tyrannical regime.",
        "year": 2006,
        "genre": "Drama, Sci-Fi, Thriller",
        "director": "Alfonso Cuarón",
        "actors": "Clive Owen, Julianne Moore, Michael Caine",
        "duration": "1h 49m",
        "rating": 7.9,
        "poster_url": "https://image.tmdb.org/t/p/w500/k9K.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=2VT2.jpg",
        "is_featured": False,
        "category": "fantastika"
      },
      {
        "title": "The Shape of Water",
        "description": "A mute custodian falls in love with an amphibious creature held captive in a 1960s lab.",
        "year": 2017,
        "genre": "Drama, Fantasy, Romance",
        "director": "Guillermo del Toro",
        "actors": "Sally Hawkins, Doug Jones, Michael Shannon",
        "duration": "2h 3m",
        "rating": 7.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/9z.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=XFYW.jpg",
        "is_featured": True,
        "category": "fantastika"
      },
      {
        "title": "Parasite",
        "description": "A poor family schemes to infiltrate a wealthy household, leading to shocking consequences.",
        "year": 2019,
        "genre": "Comedy, Drama, Thriller",
        "director": "Bong Joon-ho",
        "actors": "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong",
        "duration": "2h 12m",
        "rating": 8.5,
        "poster_url": "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=5xH0HfJHsaY",
        "is_featured": True,
        "category": "tarjima kinolar"
      },
      {
        "title": "Oldboy",
        "description": "A man, imprisoned for 15 years, seeks vengeance on those who framed him.",
        "year": 2003,
        "genre": "Action, Drama, Mystery",
        "director": "Park Chan-wook",
        "actors": "Choi Min-sik, Yoo Ji-tae, Kang Hye-jung",
        "duration": "2h 0m",
        "rating": 8.4,
        "poster_url": "https://image.tmdb.org/t/p/w500/pVscvpe.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=2HkjrJ6.jpg",
        "is_featured": False,
        "category": "tarjima kinolar"
      },
      {
        "title": "Amélie",
        "description": "A shy waitress transforms lives in Paris through small, whimsical acts of kindness.",
        "year": 2001,
        "genre": "Comedy, Romance",
        "director": "Jean-Pierre Jeunet",
        "actors": "Audrey Tautou, Mathieu Kassovitz, Rufus",
        "duration": "2h 2m",
        "rating": 8.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/fL0L.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=HUEC.jpg",
        "is_featured": True,
        "category": "tarjima kinolar"
      },
      {
        "title": "City of God",
        "description": "Two boys in a Rio de Janeiro slum take divergent paths in a world of crime.",
        "year": 2002,
        "genre": "Crime, Drama",
        "director": "Fernando Meirelles, Kátia Lund",
        "actors": "Alexandre Rodrigues, Leandro Firmino, Phellipe Haagensen",
        "duration": "2h 10m",
        "rating": 8.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/k7f.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=dcU0.jpg",
        "is_featured": True,
        "category": "tarjima kinolar"
      },
      {
        "title": "Seven Samurai",
        "description": "A village hires seven warriors to protect them from bandits in feudal Japan.",
        "year": 1954,
        "genre": "Action, Adventure, Drama",
        "director": "Akira Kurosawa",
        "actors": "Toshiro Mifune, Takashi Shimura, Keiko Tsushima",
        "duration": "3h 27m",
        "rating": 8.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/8O.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=wJ1T.jpg",
        "is_featured": False,
        "category": "tarjima kinolar"
      },
      {
        "title": "Spirited Away",
        "description": "A girl enters a spirit world to save her parents and finds her own strength in a magical bathhouse.",
        "year": 2001,
        "genre": "Animation, Adventure, Fantasy",
        "director": "Hayao Miyazaki",
        "actors": "Rumi Hiiragi, Miyu Irino, Mari Natsuki",
        "duration": "2h 5m",
        "rating": 8.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyv.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=ByXuk9QqQkk",
        "is_featured": True,
        "category": "tarjima kinolar"
      },
      {
        "title": "Crouching Tiger, Hidden Dragon",
        "description": "A stolen sword sparks a martial arts epic of love, betrayal, and destiny.",
        "year": 2000,
        "genre": "Action, Adventure, Drama",
        "director": "Ang Lee",
        "actors": "Chow Yun-Fat, Michelle Yeoh, Zhang Ziyi",
        "duration": "2h 0m",
        "rating": 7.9,
        "poster_url": "https://image.tmdb.org/t/p/w500/iND.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=pkW.jpg",
        "is_featured": True,
        "category": "tarjima kinolar"
      },
      {
        "title": "Life Is Beautiful",
        "description": "A Jewish father uses humor to shield his son from the horrors of a Nazi concentration camp.",
        "year": 1997,
        "genre": "Comedy, Drama, Romance",
        "director": "Roberto Benigni",
        "actors": "Roberto Benigni, Nicoletta Braschi, Giorgio Cantarini",
        "duration": "1h 56m",
        "rating": 8.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/74h.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=pys.jpg",
        "is_featured": True,
        "category": "tarjima kinolar"
      },
      {
        "title": "Y Tu Mamá También",
        "description": "Two teens embark on a road trip with an older woman, exploring love, friendship, and desire.",
        "year": 2001,
        "genre": "Drama",
        "director": "Alfonso Cuarón",
        "actors": "Maribel Verdú, Gael García Bernal, Diego Luna",
        "duration": "1h 46m",
        "rating": 7.7,
        "poster_url": "https://image.tmdb.org/t/p/w500/3p.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=3B.jpg",
        "is_featured": False,
        "category": "tarjima kinolar"
      },
      {
        "title": "The Lives of Others",
        "description": "A Stasi officer spying on a playwright becomes entangled in their lives in East Germany.",
        "year": 2006,
        "genre": "Drama, Thriller",
        "director": "Florian Henckel von Donnersmarck",
        "actors": "Ulrich Mühe, Martina Gedeck, Sebastian Koch",
        "duration": "2h 17m",
        "rating": 8.4,
        "poster_url": "https://image.tmdb.org/t/p/w500/6a.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=n3_i.jpg",
        "is_featured": False,
        "category": "tarjima kinolar"
      },
      {
        "title": "Rashomon",
        "description": "A crime is recounted through conflicting perspectives, exploring truth and human nature.",
        "year": 1950,
        "genre": "Crime, Drama, Mystery",
        "director": "Akira Kurosawa",
        "actors": "Toshiro Mifune, Machiko Kyō, Masayuki Mori",
        "duration": "1h 28m",
        "rating": 8.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/v8.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=xC.jpg",
        "is_featured": False,
        "category": "tarjima kinolar"
      },
      {
        "title": "The Secret in Their Eyes",
        "description": "A retired investigator revisits a decades-old murder case, uncovering love and corruption.",
        "year": 2009,
        "genre": "Drama, Mystery, Thriller",
        "director": "Juan José Campanella",
        "actors": "Ricardo Darín, Soledad Villamil, Pablo Rago",
        "duration": "2h 9m",
        "rating": 8.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/h8.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=1T.jpg",
        "is_featured": True,
        "category": "tarjima kinolar"
      },
      {
        "title": "A Separation",
        "description": "A couple faces a moral dilemma when their marriage and a hired caretaker's life collide.",
        "year": 2011,
        "genre": "Drama",
        "director": "Asghar Farhadi",
        "actors": "Payman Maadi, Leila Hatami, Sareh Bayat",
        "duration": "2h 3m",
        "rating": 8.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/w0.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=6T.jpg",
        "is_featured": True,
        "category": "tarjima kinolar"
      },
      {
        "title": "The Handmaiden",
        "description": "A conman and a pickpocket plot to deceive a wealthy heiress, leading to unexpected twists.",
        "year": 2016,
        "genre": "Drama, Romance, Thriller",
        "director": "Park Chan-wook",
        "actors": "Kim Min-hee, Ha Jung-woo, Cho Jin-woong",
        "duration": "2h 25m",
        "rating": 8.1,
        "poster_url": "https://image.tmdb.org/t/p/w500/p0.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=whl.jpg",
        "is_featured": True,
        "category": "tarjima kinolar"
      },
      {
        "title": "Memories of Murder",
        "description": "Two detectives investigate a series of brutal murders in rural South Korea.",
        "year": 2003,
        "genre": "Crime, Drama, Mystery",
        "director": "Bong Joon-ho",
        "actors": "Song Kang-ho, Kim Sang-kyung, Roe-ha Kim",
        "duration": "2h 11m",
        "rating": 8.1,
        "poster_url": "https://image.tmdb.org/t/p/w500/z9.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=s3.jpg",
        "is_featured": False,
        "category": "tarjima kinolar"
      },
      {
        "title": "Wild Tales",
        "description": "An anthology of darkly comedic stories about revenge, betrayal, and human extremes.",
        "year": 2014,
        "genre": "Comedy, Drama, Thriller",
        "director": "Damián Szifron",
        "actors": "Ricardo Darín, Oscar Martínez, Leonardo Sbaraglia",
        "duration": "2h 2m",
        "rating": 8.1,
        "poster_url": "https://image.tmdb.org/t/p/w500/l2.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=9B.jpg",
        "is_featured": True,
        "category": "tarjima kinolar"
      },
      {
        "title": "The Intouchables",
        "description": "A wealthy paraplegic and his ex-con caregiver form an unlikely bond in Paris.",
        "year": 2011,
        "genre": "Biography, Comedy, Drama",
        "director": "Olivier Nakache, Éric Toledano",
        "actors": "François Cluzet, Omar Sy, Anne Le Ny",
        "duration": "1h 52m",
        "rating": 8.5,
        "poster_url": "https://image.tmdb.org/t/p/w500/t1.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=34W.jpg",
        "is_featured": True,
        "category": "tarjima kinolar"
      },
      {
        "title": "Incendies",
        "description": "Twins uncover their mother's tragic past in a war-torn Middle Eastern country.",
        "year": 2010,
        "genre": "Drama, Mystery",
        "director": "Denis Villeneuve",
        "actors": "Lubna Azabal, Mélissa Désormeaux-Poulin, Maxim Gaudette",
        "duration": "2h 11m",
        "rating": 8.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/sE.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=0W.jpg",
        "is_featured": False,
        "category": "tarjima kinolar"
      },
      {
        "title": "Pan's Labyrinth",
        "description": "A girl discovers a mythical labyrinth and tasks from a faun amid Spain's civil war horrors.",
        "year": 2006,
        "genre": "Drama, Fantasy",
        "director": "Guillermo del Toro",
        "actors": "Ivana Baquero, Sergi López, Maribel Verdú",
        "duration": "1h 58m",
        "rating": 8.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/zp6Z.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=EqYi.jpg",
        "is_featured": True,
        "category": "tarjima kinolar"
      },
      {
        "title": "The Motorcycle Diaries",
        "description": "Young Che Guevara embarks on a transformative road trip across South America.",
        "year": 2004,
        "genre": "Adventure, Biography, Drama",
        "director": "Walter Salles",
        "actors": "Gael García Bernal, Rodrigo de la Serna, Mía Maestro",
        "duration": "2h 6m",
        "rating": 7.7,
        "poster_url": "https://image.tmdb.org/t/p/w500/v3.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=1p.jpg",
        "is_featured": False,
        "category": "tarjima kinolar"
      },
      {
        "title": "Dune: Part Two",
        "description": "Paul Atreides continues his journey to unite the Fremen and challenge the galactic empire.",
        "year": 2024,
        "genre": "Adventure, Sci-Fi, Drama",
        "director": "Denis Villeneuve",
        "actors": "Timothée Chalamet, Zendaya, Florence Pugh",
        "duration": "2h 46m",
        "rating": 8.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/1pfNbkW.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=Way9Dexny3w",
        "is_featured": True,
        "category": "premyera"
      },
      {
        "title": "Oppenheimer",
        "description": "The story of J. Robert Oppenheimer and the creation of the atomic bomb.",
        "year": 2023,
        "genre": "Biography, Drama, History",
        "director": "Christopher Nolan",
        "actors": "Cillian Murphy, Emily Blunt, Matt Damon",
        "duration": "3h 0m",
        "rating": 8.4,
        "poster_url": "https://image.tmdb.org/t/p/w500/8Gxv8gS.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=uYPbbksJxIg",
        "is_featured": True,
        "category": "premyera"
      },
      {
        "title": "Barbie",
        "description": "Barbie leaves her perfect world to explore the real world, sparking self-discovery.",
        "year": 2023,
        "genre": "Comedy, Fantasy",
        "director": "Greta Gerwig",
        "actors": "Margot Robbie, Ryan Gosling, America Ferrera",
        "duration": "1h 54m",
        "rating": 7.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/iuFNMS8.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=pBk4NYhWNMM",
        "is_featured": True,
        "category": "premyera"
      },
      {
        "title": "Mission: Impossible – Dead Reckoning Part One",
        "description": "Ethan Hunt races to stop a rogue AI from causing global chaos.",
        "year": 2023,
        "genre": "Action, Adventure, Thriller",
        "director": "Christopher McQuarrie",
        "actors": "Tom Cruise, Hayley Atwell, Ving Rhames",
        "duration": "2h 43m",
        "rating": 7.7,
        "poster_url": "https://image.tmdb.org/t/p/w500/NNxYkU.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=avz06HtxHgA",
        "is_featured": True,
        "category": "premyera"
      },
      {
        "title": "The Batman",
        "description": "A young Batman investigates a series of murders tied to Gotham's elite.",
        "year": 2022,
        "genre": "Action, Crime, Drama",
        "director": "Matt Reeves",
        "actors": "Robert Pattinson, Zoë Kravitz, Paul Dano",
        "duration": "2h 56m",
        "rating": 7.8,
        "poster_url": "https://image.tmdb.org/t/p/w500/74xTEgt.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=mqqft2x_Aa4",
        "is_featured": True,
        "category": "premyera"
      },
      {
        "title": "Spider-Man: Across the Spider-Verse",
        "description": "Miles Morales embarks on a multiversal adventure to save every universe.",
        "year": 2023,
        "genre": "Animation, Action, Adventure",
        "director": "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson",
        "actors": "Shameik Moore, Hailee Steinfeld, Brian Tyree Henry",
        "duration": "2h 20m",
        "rating": 8.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/8Vt6m.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=shW9i6k8G98",
        "is_featured": True,
        "category": "premyera"
      },
      {
        "title": "Poor Things",
        "description": "A woman brought back to life embarks on a journey of self-discovery and liberation.",
        "year": 2023,
        "genre": "Comedy, Drama, Sci-Fi",
        "director": "Yorgos Lanthimos",
        "actors": "Emma Stone, Mark Ruffalo, Willem Dafoe",
        "duration": "2h 21m",
        "rating": 8.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/kC7.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=RlbR5N6veqw",
        "is_featured": True,
        "category": "premyera"
      },
      {
        "title": "Everything Everywhere All at Once",
        "description": "A woman navigates multiple universes to save reality and reconnect with her family.",
        "year": 2022,
        "genre": "Action, Adventure, Comedy",
        "director": "Daniel Kwan, Daniel Scheinert",
        "actors": "Michelle Yeoh, Stephanie Hsu, Ke Huy Quan",
        "duration": "2h 19m",
        "rating": 7.8,
        "poster_url": "https://image.tmdb.org/t/p/w500/w3L.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=wxN1T1uxQ2g",
        "is_featured": True,
        "category": "premyera"
      },
      {
        "title": "Top Gun: Maverick",
        "description": "A veteran pilot trains a new generation for a dangerous mission.",
        "year": 2022,
        "genre": "Action, Drama",
        "director": "Joseph Kosinski",
        "actors": "Tom Cruise, Miles Teller, Jennifer Connelly",
        "duration": "2h 11m",
        "rating": 8.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/62H.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=giXco2jaZ_4",
        "is_featured": True,
        "category": "premyera"
      },
      {
        "title": "Avatar: The Way of Water",
        "description": "Jake Sully and his family fight to protect Pandora from a new human threat.",
        "year": 2022,
        "genre": "Action, Adventure, Sci-Fi",
        "director": "James Cameron",
        "actors": "Sam Worthington, Zoe Saldana, Sigourney Weaver",
        "duration": "3h 12m",
        "rating": 7.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/t6H.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=d9MyW72ELq0",
        "is_featured": True,
        "category": "premyera"
      },
      {
        "title": "The Menu",
        "description": "A couple dines at an exclusive restaurant where the chef has sinister plans.",
        "year": 2022,
        "genre": "Comedy, Horror, Thriller",
        "director": "Mark Mylod",
        "actors": "Ralph Fiennes, Anya Taylor-Joy, Nicholas Hoult",
        "duration": "1h 47m",
        "rating": 7.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/v.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=C_uTkUGcHv4",
        "is_featured": False,
        "category": "premyera"
      },
      {
        "title": "Killers of the Flower Moon",
        "description": "A series of murders in 1920s Oklahoma uncovers a chilling conspiracy.",
        "year": 2023,
        "genre": "Crime, Drama, History",
        "director": "Martin Scorsese",
        "actors": "Leonardo DiCaprio, Robert De Niro, Lily Gladstone",
        "duration": "3h 26m",
        "rating": 7.7,
        "poster_url": "https://image.tmdb.org/t/p/w500/dB.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=EP34Yoxs3FQ",
        "is_featured": True,
        "category": "premyera"
      },
      {
        "title": "The Zone of Interest",
        "description": "A Nazi officer's family lives an idyllic life next to Auschwitz, ignoring its horrors.",
        "year": 2023,
        "genre": "Drama, History",
        "director": "Jonathan Glazer",
        "actors": "Christian Friedel, Sandra Hüller, Johann Karthaus",
        "duration": "1h 45m",
        "rating": 7.5,
        "poster_url": "https://image.tmdb.org/t/p/w500/k2.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=r-vfg3KkV8s",
        "is_featured": False,
        "category": "premyera"
      },
      {
        "title": "Furiosa: A Mad Max Saga",
        "description": "Young Furiosa's origin story unfolds in a post-apocalyptic wasteland.",
        "year": 2024,
        "genre": "Action, Adventure, Sci-Fi",
        "director": "George Miller",
        "actors": "Anya Taylor-Joy, Chris Hemsworth, Tom Burke",
        "duration": "2h 28m",
        "rating": 7.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/x.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=FVswuip0CoY",
        "is_featured": True,
        "category": "premyera"
      },
      {
        "title": "Challengers",
        "description": "A tennis player turned coach navigates a love triangle in the competitive sports world.",
        "year": 2024,
        "genre": "Drama, Romance, Sport",
        "director": "Luca Guadagnino",
        "actors": "Zendaya, Mike Faist, Josh O'Connor",
        "duration": "2h 11m",
        "rating": 7.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/3.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=OzZYwSv3flU",
        "is_featured": False,
        "category": "premyera"
      },
      {
        "title": "The Fall Guy",
        "description": "A stuntman searches for a missing actor while working on his ex-girlfriend’s film.",
        "year": 2024,
        "genre": "Action, Comedy, Drama",
        "director": "David Leitch",
        "actors": "Ryan Gosling, Emily Blunt, Aaron Taylor-Johnson",
        "duration": "2h 6m",
        "rating": 7.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/a.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=7L2YJ2Zy3gI",
        "is_featured": False,
        "category": "premyera"
      },
      {
        "title": "Napoleon",
        "description": "The rise and fall of Napoleon Bonaparte, focusing on his military and personal life.",
        "year": 2023,
        "genre": "Action, Biography, Drama",
        "director": "Ridley Scott",
        "actors": "Joaquin Phoenix, Vanessa Kirby, Tahar Rahim",
        "duration": "2h 38m",
        "rating": 6.5,
        "poster_url": "https://image.tmdb.org/t/p/w500/j.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=OAZwxSBV_I8",
        "is_featured": False,
        "category": "premyera"
      },
      {
        "title": "Wicked",
        "description": "The untold story of the witches of Oz, exploring their friendship and rivalry.",
        "year": 2024,
        "genre": "Fantasy, Musical",
        "director": "Jon M. Chu",
        "actors": "Cynthia Erivo, Ariana Grande, Jonathan Bailey",
        "duration": "2h 40m",
        "rating": 7.5,
        "poster_url": "https://image.tmdb.org/t/p/w500/w.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=F1d0K9C4Q8s",
        "is_featured": True,
        "category": "premyera"
      },
      {
        "title": "The Creator",
        "description": "A soldier hunts an AI weapon in a war-torn future, uncovering moral dilemmas.",
        "year": 2023,
        "genre": "Action, Sci-Fi, Thriller",
        "director": "Gareth Edwards",
        "actors": "John David Washington, Madeleine Yuna Voyles, Gemma Chan",
        "duration": "2h 13m",
        "rating": 6.8,
        "poster_url": "https://image.tmdb.org/t/p/w500/z.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=ex3C1-5Dhb8",
        "is_featured": False,
        "category": "premyera"
      },
      {
        "title": "A Haunting in Venice",
        "description": "Hercule Poirot solves a supernatural mystery at a séance in post-WWII Venice.",
        "year": 2023,
        "genre": "Crime, Drama, Mystery",
        "director": "Kenneth Branagh",
        "actors": "Kenneth Branagh, Michelle Yeoh, Jamie Dornan",
        "duration": "1h 43m",
        "rating": 6.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/h.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=2oJ-4eM3v4c",
        "is_featured": False,
        "category": "premyera"
      },
      {
        "title": "Dangal",
        "description": "A former wrestler trains his daughters to become world-class wrestlers.",
        "year": 2016,
        "genre": "Biography, Drama, Sport",
        "director": "Nitesh Tiwari",
        "actors": "Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh",
        "duration": "2h 41m",
        "rating": 8.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/sS.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=x_7YlGv9u1g",
        "is_featured": True,
        "category": "hind kinolari"
      },
      {
        "title": "3 Idiots",
        "description": "Three college friends challenge the rigid education system and pursue their dreams.",
        "year": 2009,
        "genre": "Comedy, Drama",
        "director": "Rajkumar Hirani",
        "actors": "Aamir Khan, Kareena Kapoor, R. Madhavan",
        "duration": "2h 50m",
        "rating": 8.4,
        "poster_url": "https://image.tmdb.org/t/p/w500/6F.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=xvszmNXdM4w",
        "is_featured": True,
        "category": "hind kinolari"
      },
      {
        "title": "PK",
        "description": "An alien stranded on Earth questions religious dogmas while searching for his lost device.",
        "year": 2014,
        "genre": "Comedy, Drama, Sci-Fi",
        "director": "Rajkumar Hirani",
        "actors": "Aamir Khan, Anushka Sharma, Sanjay Dutt",
        "duration": "2h 33m",
        "rating": 8.1,
        "poster_url": "https://image.tmdb.org/t/p/w500/x.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=SOXWc32k4zA",
        "is_featured": True,
        "category": "hind kinolari"
      },
      {
        "title": "Bajrangi Bhaijaan",
        "description": "A man helps a mute Pakistani girl return home, facing challenges across borders.",
        "year": 2015,
        "genre": "Action, Adventure, Drama",
        "director": "Kabir Khan",
        "actors": "Salman Khan, Harshaali Malhotra, Nawazuddin Siddiqui",
        "duration": "2h 39m",
        "rating": 8.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/r.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=6xZr1WfxPdo",
        "is_featured": True,
        "category": "hind kinolari"
      },
      {
        "title": "Lagaan",
        "description": "Villagers in colonial India challenge British rulers to a cricket match to avoid taxes.",
        "year": 2001,
        "genre": "Drama, Sport",
        "director": "Ashutosh Gowariker",
        "actors": "Aamir Khan, Gracy Singh, Rachel Shelley",
        "duration": "3h 44m",
        "rating": 8.1,
        "poster_url": "https://image.tmdb.org/t/p/w500/y.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=6G5f6mzv3Q0",
        "is_featured": False,
        "category": "hind kinolari"
      },
      {
        "title": "Dilwale Dulhania Le Jayenge",
        "description": "Two young lovers defy cultural traditions to be together in a romantic epic.",
        "year": 1995,
        "genre": "Drama, Romance",
        "director": "Aditya Chopra",
        "actors": "Shah Rukh Khan, Kajol, Amrish Puri",
        "duration": "3h 9m",
        "rating": 8.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/2.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=cmax1C1k_raw",
        "is_featured": True,
        "category": "hind kinolari"
      },
      {
        "title": "Queen",
        "description": "A shy woman embarks on a solo honeymoon, discovering her strength and independence.",
        "year": 2013,
        "genre": "Comedy, Drama",
        "director": "Vikas Bahl",
        "actors": "Kangana Ranaut, Rajkummar Rao, Lisa Haydon",
        "duration": "2h 26m",
        "rating": 8.1,
        "poster_url": "https://image.tmdb.org/t/p/w500/q.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=KGC6vl3lU0o",
        "is_featured": False,
        "category": "hind kinolari"
      },
      {
        "title": "Baahubali: The Beginning",
        "description": "A young man discovers his royal heritage and fights to reclaim his kingdom.",
        "year": 2015,
        "genre": "Action, Drama",
        "director": "S.S. Rajamouli",
        "actors": "Prabhas, Rana Daggubati, Anushka Shetty",
        "duration": "2h 39m",
        "rating": 8.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/9B.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=sOEg_YZQsTI",
        "is_featured": True,
        "category": "hind kinolari"
      },
      {
        "title": "Baahubali 2: The Conclusion",
        "description": "The epic saga continues as a prince battles to avenge his family and claim the throne.",
        "year": 2017,
        "genre": "Action, Drama",
        "director": "S.S. Rajamouli",
        "actors": "Prabhas, Rana Daggubati, Anushka Shetty",
        "duration": "2h 47m",
        "rating": 8.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/z.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=qD-6d8Wo3do",
        "is_featured": True,
        "category": "hind kinolari"
      },
      {
        "title": "Padmaavat",
        "description": "A queen faces a ruthless sultan's obsession in a tale of love and war.",
        "year": 2018,
        "genre": "Drama, History, Romance",
        "director": "Sanjay Leela Bhansali",
        "actors": "Deepika Padukone, Ranveer Singh, Shahid Kapoor",
        "duration": "2h 44m",
        "rating": 7.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/7.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=X_5_BLt76c0",
        "is_featured": False,
        "category": "hind kinolari"
      },
      {
        "title": "Andhadhun",
        "description": "A blind pianist gets entangled in a murder mystery with unexpected twists.",
        "year": 2018,
        "genre": "Crime, Mystery, Thriller",
        "director": "Sriram Raghavan",
        "actors": "Ayushmann Khurrana, Tabu, Radhika Apte",
        "duration": "2h 19m",
        "rating": 8.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/a.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=2iVYI99VGaw",
        "is_featured": True,
        "category": "hind kinolari"
      },
      {
        "title": "Drishyam",
        "description": "A man goes to great lengths to protect his family after an accidental crime.",
        "year": 2015,
        "genre": "Crime, Drama, Thriller",
        "director": "Nishikant Kamat",
        "actors": "Ajay Devgn, Shriya Saran, Tabu",
        "duration": "2h 43m",
        "rating": 8.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/3.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=AuuX2j0Vscg",
        "is_featured": False,
        "category": "hind kinolari"
      },
      {
        "title": "Kabir Singh",
        "description": "A brilliant but self-destructive surgeon spirals after his lover is forced to marry another.",
        "year": 2019,
        "genre": "Drama, Romance",
        "director": "Sandeep Reddy Vanga",
        "actors": "Shahid Kapoor, Kiara Advani, Arjan Bajwa",
        "duration": "2h 52m",
        "rating": 7.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/2.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=RzO_s6xTwnA",
        "is_featured": False,
        "category": "hind kinolari"
      },
      {
        "title": "Uri: The Surgical Strike",
        "description": "Indian soldiers execute a covert operation to avenge a terrorist attack.",
        "year": 2019,
        "genre": "Action, Drama, War",
        "director": "Aditya Dhar",
        "actors": "Vicky Kaushal, Paresh Rawal, Yami Gautam",
        "duration": "2h 18m",
        "rating": 8.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/v.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=VVz6Y3h3yU0",
        "is_featured": True,
        "category": "hind kinolari"
      },
      {
        "title": "Gully Boy",
        "description": "A street rapper from Mumbai’s slums rises to fame with his raw talent.",
        "year": 2019,
        "genre": "Drama, Music",
        "director": "Zoya Akhtar",
        "actors": "Ranveer Singh, Alia Bhatt, Siddhant Chaturvedi",
        "duration": "2h 34m",
        "rating": 7.9,
        "poster_url": "https://image.tmdb.org/t/p/w500/g.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=JfbxcD_kClY",
        "is_featured": True,
        "category": "hind kinolari"
      },
      {
        "title": "Barfi!",
        "description": "A mute and deaf man forms a bond with two women in a heartwarming tale.",
        "year": 2012,
        "genre": "Comedy, Drama, Romance",
        "director": "Anurag Basu",
        "actors": "Ranbir Kapoor, Priyanka Chopra, Ileana D'Cruz",
        "duration": "2h 31m",
        "rating": 8.1,
        "poster_url": "https://image.tmdb.org/t/p/w500/5.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=3R.jpg",
        "is_featured": False,
        "category": "hind kinolari"
      },
      {
        "title": "Taare Zameen Par",
        "description": "A dyslexic child finds his potential with the help of an inspiring teacher.",
        "year": 2007,
        "genre": "Drama, Family",
        "director": "Aamir Khan",
        "actors": "Darsheel Safary, Aamir Khan, Tisca Chopra",
        "duration": "2h 45m",
        "rating": 8.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/2.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=9N.jpg",
        "is_featured": True,
        "category": "hind kinolari"
      },
      {
        "title": "Chennai Express",
        "description": "A man’s train journey turns into an adventure when he helps a runaway bride.",
        "year": 2013,
        "genre": "Action, Comedy, Romance",
        "director": "Rohit Shetty",
        "actors": "Shah Rukh Khan, Deepika Padukone, Nikitin Dheer",
        "duration": "2h 21m",
        "rating": 6.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/3.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=3q.jpg",
        "is_featured": False,
        "category": "hind kinolari"
      },
      {
        "title": "Swades",
        "description": "An Indian scientist returns to his village, sparking change and self-discovery.",
        "year": 2004,
        "genre": "Drama",
        "director": "Ashutosh Gowariker",
        "actors": "Shah Rukh Khan, Gayatri Joshi, Kishori Ballal",
        "duration": "3h 9m",
        "rating": 8.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/7.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=1H.jpg",
        "is_featured": False,
        "category": "hind kinolari"
      },
      {
        "title": "Zindagi Na Milegi Dobara",
        "description": "Three friends embark on a life-changing road trip through Spain.",
        "year": 2011,
        "genre": "Comedy, Drama",
        "director": "Zoya Akhtar",
        "actors": "Hrithik Roshan, Farhan Akhtar, Abhay Deol",
        "duration": "2h 35m",
        "rating": 8.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/2.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=9N.jpg",
        "is_featured": True,
        "category": "hind kinolari"
      },
      {
        "title": "The Lion King",
        "description": "A young lion prince must reclaim his kingdom after his father’s tragic death.",
        "year": 1994,
        "genre": "Animation, Adventure, Drama",
        "director": "Roger Allers, Rob Minkoff",
        "actors": "Matthew Broderick, Jeremy Irons, James Earl Jones",
        "duration": "1h 28m",
        "rating": 8.5,
        "poster_url": "https://image.tmdb.org/t/p/w500/sKCr78.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=4sj1MT05lAA",
        "is_featured": True,
        "category": "multfilmlar"
      },
      {
        "title": "Toy Story",
        "description": "A cowboy doll faces rivalry with a new action figure, leading to an adventure.",
        "year": 1995,
        "genre": "Animation, Adventure, Comedy",
        "director": "John Lasseter",
        "actors": "Tom Hanks, Tim Allen, Don Rickles",
        "duration": "1h 21m",
        "rating": 8.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/u.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=KYz2wyBy3kc",
        "is_featured": True,
        "category": "multfilmlar"
      },
      {
        "title": "Finding Nemo",
        "description": "A clownfish searches for his missing son across the vast ocean.",
        "year": 2003,
        "genre": "Animation, Adventure, Comedy",
        "director": "Andrew Stanton, Lee Unkrich",
        "actors": "Albert Brooks, Ellen DeGeneres, Alexander Gould",
        "duration": "1h 40m",
        "rating": 8.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/e.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=wZdpNglLbt8",
        "is_featured": True,
        "category": "multfilmlar"
      },
      {
        "title": "Spirited Away",
        "description": "A girl navigates a magical spirit world to save her parents and find herself.",
        "year": 2001,
        "genre": "Animation, Adventure, Fantasy",
        "director": "Hayao Miyazaki",
        "actors": "Rumi Hiiragi, Miyu Irino, Mari Natsuki",
        "duration": "2h 5m",
        "rating": 8.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyv.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=ByXuk9QqQkk",
        "is_featured": True,
        "category": "multfilmlar"
      },
      {
        "title": "WALL-E",
        "description": "A lonely robot on a deserted Earth finds love and a mission to save humanity.",
        "year": 2008,
        "genre": "Animation, Adventure, Sci-Fi",
        "director": "Andrew Stanton",
        "actors": "Ben Burtt, Elissa Knight, Jeff Garlin",
        "duration": "1h 38m",
        "rating": 8.4,
        "poster_url": "https://image.tmdb.org/t/p/w500/9.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=CZ1CATNbXg0",
        "is_featured": True,
        "category": "multfilmlar"
      },
      {
        "title": "Up",
        "description": "An elderly man flies his house to South America, joined by an unexpected stowaway.",
        "year": 2009,
        "genre": "Animation, Adventure, Comedy",
        "director": "Pete Docter, Bob Peterson",
        "actors": "Ed Asner, Jordan Nagai, John Ratzenberger",
        "duration": "1h 36m",
        "rating": 8.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/v.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=pkqzFUhGPOM",
        "is_featured": True,
        "category": "multfilmlar"
      },
      {
        "title": "Inside Out",
        "description": "A girl’s emotions navigate her mind as she faces major life changes.",
        "year": 2015,
        "genre": "Animation, Adventure, Comedy",
        "director": "Pete Docter, Ronnie Del Carmen",
        "actors": "Amy Poehler, Bill Hader, Lewis Black",
        "duration": "1h 35m",
        "rating": 8.1,
        "poster_url": "https://image.tmdb.org/t/p/w500/2.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=seMwpP0iu_c",
        "is_featured": True,
        "category": "multfilmlar"
      },
      {
        "title": "Coco",
        "description": "A boy journeys to the Land of the Dead to uncover his family’s musical legacy.",
        "year": 2017,
        "genre": "Animation, Adventure, Family",
        "director": "Lee Unkrich, Adrian Molina",
        "actors": "Anthony Gonzalez, Gael García Bernal, Benjamin Bratt",
        "duration": "1h 45m",
        "rating": 8.4,
        "poster_url": "https://image.tmdb.org/t/p/w500/g.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=Rvr68u6k5sI",
        "is_featured": True,
        "category": "multfilmlar"
      },
      {
        "title": "How to Train Your Dragon",
        "description": "A young Viking befriends a dragon, challenging his tribe’s traditions.",
        "year": 2010,
        "genre": "Animation, Action, Adventure",
        "director": "Chris Sanders, Dean DeBlois",
        "actors": "Jay Baruchel, Gerard Butler, Craig Ferguson",
        "duration": "1h 38m",
        "rating": 8.1,
        "poster_url": "https://image.tmdb.org/t/p/w500/3.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=oKiYuIsUCYg",
        "is_featured": True,
        "category": "multfilmlar"
      },
      {
        "title": "Zootopia",
        "description": "A rookie bunny cop teams with a fox to solve a mystery in a bustling animal city.",
        "year": 2016,
        "genre": "Animation, Adventure, Comedy",
        "director": "Byron Howard, Rich Moore",
        "actors": "Ginnifer Goodwin, Jason Bateman, Idris Elba",
        "duration": "1h 48m",
        "rating": 8.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/2.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=jWM0ct-6DDg",
        "is_featured": True,
        "category": "multfilmlar"
      },
      {
        "title": "Frozen",
        "description": "A fearless princess sets off to find her sister and save their kingdom from eternal winter.",
        "year": 2013,
        "genre": "Animation, Adventure, Comedy",
        "director": "Chris Buck, Jennifer Lee",
        "actors": "Kristen Bell, Idina Menzel, Jonathan Groff",
        "duration": "1h 42m",
        "rating": 7.4,
        "poster_url": "https://image.tmdb.org/t/p/w500/k.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=TbQm5doF_Uc",
        "is_featured": True,
        "category": "multfilmlar"
      },
      {
        "title": "The Incredibles",
        "description": "A superhero family comes out of hiding to battle a new villain.",
        "year": 2004,
        "genre": "Animation, Action, Adventure",
        "director": "Brad Bird",
        "actors": "Craig T. Nelson, Holly Hunter, Samuel L. Jackson",
        "duration": "1h 55m",
        "rating": 8.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/2.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=eZbzbC9285I",
        "is_featured": True,
        "category": "multfilmlar"
      },
      {
        "title": "Moana",
        "description": "A young girl sails across the ocean to save her people with a demigod’s help.",
        "year": 2016,
        "genre": "Animation, Adventure, Comedy",
        "director": "Ron Clements, John Musker",
        "actors": "Auliʻi Cravalho, Dwayne Johnson, Rachel House",
        "duration": "1h 47m",
        "rating": 7.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/4.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=LKFuXzG5MgY",
        "is_featured": True,
        "category": "multfilmlar"
      },
      {
        "title": "Shrek",
        "description": "An ogre teams up with a donkey to rescue a princess and save his swamp.",
        "year": 2001,
        "genre": "Animation, Adventure, Comedy",
        "director": "Andrew Adamson, Vicky Jenson",
        "actors": "Mike Myers, Eddie Murphy, Cameron Diaz",
        "duration": "1h 30m",
        "rating": 7.9,
        "poster_url": "https://image.tmdb.org/t/p/w500/i.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=CwXOrW2iMWe",
        "is_featured": True,
        "category": "multfilmlar"
      },
      {
        "title": "Kung Fu Panda",
        "description": "A clumsy panda becomes an unlikely martial arts hero to save the valley.",
        "year": 2008,
        "genre": "Animation, Action, Comedy",
        "director": "Mark Osborne, John Stevenson",
        "actors": "Jack Black, Dustin Hoffman, Angelina Jolie",
        "duration": "1h 32m",
        "rating": 7.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/w.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=PXi3Mv6KMzY",
        "is_featured": False,
        "category": "multfilmlar"
      },
      {
        "title": "Ratatouille",
        "description": "A rat with a passion for cooking teams up with a young chef in Paris.",
        "year": 2007,
        "genre": "Animation, Comedy, Family",
        "director": "Brad Bird, Jan Pinkava",
        "actors": "Patton Oswalt, Ian Holm, Lou Romano",
        "duration": "1h 51m",
        "rating": 8.1,
        "poster_url": "https://image.tmdb.org/t/p/w500/2.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=NgsQ8mVkN8w",
        "is_featured": True,
        "category": "multfilmlar"
      },
      {
        "title": "Big Hero 6",
        "description": "A young robotics genius and his inflatable robot save their city from a villain.",
        "year": 2014,
        "genre": "Animation, Action, Adventure",
        "director": "Don Hall, Chris Williams",
        "actors": "Scott Adsit, Ryan Potter, Daniel Henney",
        "duration": "1h 42m",
        "rating": 7.8,
        "poster_url": "https://image.tmdb.org/t/p/w500/3.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=z3biFxZIJOQ",
        "is_featured": True,
        "category": "multfilmlar"
      },
      {
        "title": "Tangled",
        "description": "A princess with magical hair escapes her tower with a charming thief.",
        "year": 2010,
        "genre": "Animation, Adventure, Comedy",
        "director": "Nathan Greno, Byron Howard",
        "actors": "Mandy Moore, Zachary Levi, Donna Murphy",
        "duration": "1h 40m",
        "rating": 7.7,
        "poster_url": "https://image.tmdb.org/t/p/w500/y.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=ip_0CFKTO9E",
        "is_featured": True,
        "category": "multfilmlar"
      },
      {
        "title": "The Nightmare Before Christmas",
        "description": "The Pumpkin King discovers Christmas and tries to blend it with Halloween.",
        "year": 1993,
        "genre": "Animation, Family, Fantasy",
        "director": "Henry Selick",
        "actors": "Danny Elfman, Chris Sarandon, Catherine O'Hara",
        "duration": "1h 16m",
        "rating": 7.9,
        "poster_url": "https://image.tmdb.org/t/p/w500/o.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=wr6N_hZyBCk",
        "is_featured": False,
        "category": "multfilmlar"
      },
      {
        "title": "Soul",
        "description": "A musician’s soul embarks on a journey to find his passion for life.",
        "year": 2020,
        "genre": "Animation, Adventure, Comedy",
        "director": "Pete Docter, Kemp Powers",
        "actors": "Jamie Foxx, Tina Fey, Graham Norton",
        "duration": "1h 40m",
        "rating": 8.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/h.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=xOsLIiBStEs",
        "is_featured": True,
        "category": "multfilmlar"
      },
      {
        "title": "The Godfather",
        "description": "A mafia patriarch transfers control of his empire to his reluctant son.",
        "year": 1972,
        "genre": "Crime, Drama",
        "director": "Francis Ford Coppola",
        "actors": "Marlon Brando, Al Pacino, James Caan",
        "duration": "2h 55m",
        "rating": 9.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/3.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=sY1S34973zA",
        "is_featured": True,
        "category": "klassika"
      },
      {
        "title": "Citizen Kane",
        "description": "A newspaper tycoon’s life is explored through the mystery of his final word.",
        "year": 1941,
        "genre": "Drama, Mystery",
        "director": "Orson Welles",
        "actors": "Orson Welles, Joseph Cotten, Dorothy Comingore",
        "duration": "1h 59m",
        "rating": 8.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/s.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=8dxh3lwdOFw",
        "is_featured": True,
        "category": "klassika"
      },
      {
        "title": "Casablanca",
        "description": "A nightclub owner faces love and sacrifice in WWII-era Morocco.",
        "year": 1942,
        "genre": "Drama, Romance",
        "director": "Michael Curtiz",
        "actors": "Humphrey Bogart, Ingrid Bergman, Paul Henreid",
        "duration": "1h 42m",
        "rating": 8.5,
        "poster_url": "https://image.tmdb.org/t/p/w500/5.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=BkL9l7qovsE",
        "is_featured": True,
        "category": "klassika"
      },
      {
        "title": "Gone with the Wind",
        "description": "A Southern belle navigates love and survival during the Civil War.",
        "year": 1939,
        "genre": "Drama, History, Romance",
        "director": "Victor Fleming",
        "actors": "Vivien Leigh, Clark Gable, Olivia de Havilland",
        "duration": "3h 58m",
        "rating": 8.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/4.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=0X94oZgJ.jpg",
        "is_featured": True,
        "category": "klassika"
      },
      {
        "title": "The Shawshank Redemption",
        "description": "A banker wrongfully imprisoned forms a bond with a fellow inmate over decades.",
        "year": 1994,
        "genre": "Drama",
        "director": "Frank Darabont",
        "actors": "Tim Robbins, Morgan Freeman, Bob Gunton",
        "duration": "2h 22m",
        "rating": 9.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/q.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=6hB3S9bIaco",
        "is_featured": True,
        "category": "klassika"
      },
      {
        "title": "Schindler's List",
        "description": "A businessman saves Jewish refugees during the Holocaust by employing them.",
        "year": 1993,
        "genre": "Biography, Drama, History",
        "director": "Steven Spielberg",
        "actors": "Liam Neeson, Ralph Fiennes, Ben Kingsley",
        "duration": "3h 15m",
        "rating": 9.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/s.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=gG22xn8M8qw",
        "is_featured": True,
        "category": "klassika"
      },
      {
        "title": "Pulp Fiction",
        "description": "Interwoven stories of criminals, hitmen, and a boxer in a nonlinear crime saga.",
        "year": 1994,
        "genre": "Crime, Drama",
        "director": "Quentin Tarantino",
        "actors": "John Travolta, Uma Thurman, Samuel L. Jackson",
        "duration": "2h 34m",
        "rating": 8.9,
        "poster_url": "https://image.tmdb.org/t/p/w500/d.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=s7EdQ4fzBhY",
        "is_featured": True,
        "category": "klassika"
      },
      {
        "title": "12 Angry Men",
        "description": "A jury debates the fate of a young man accused of murder in a tense drama.",
        "year": 1957,
        "genre": "Crime, Drama",
        "director": "Sidney Lumet",
        "actors": "Henry Fonda, Lee J. Cobb, Martin Balsam",
        "duration": "1h 36m",
        "rating": 9.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/o.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=A7CBKT0PWFA",
        "is_featured": True,
        "category": "klassika"
      },
      {
        "title": "The Good, the Bad and the Ugly",
        "description": "Three gunslingers hunt for buried treasure during the Civil War.",
        "year": 1966,
        "genre": "Western",
        "director": "Sergio Leone",
        "actors": "Clint Eastwood, Eli Wallach, Lee Van Cleef",
        "duration": "2h 41m",
        "rating": 8.8,
        "poster_url": "https://image.tmdb.org/t/p/w500/b.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=WCN5JJY_wiA",
        "is_featured": True,
        "category": "klassika"
      },
      {
        "title": "Psycho",
        "description": "A woman on the run checks into a motel with a dangerous secret.",
        "year": 1960,
        "genre": "Horror, Mystery, Thriller",
        "director": "Alfred Hitchcock",
        "actors": "Anthony Perkins, Janet Leigh, Vera Miles",
        "duration": "1h 49m",
        "rating": 8.5,
        "poster_url": "https://image.tmdb.org/t/p/w500/6.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=DTJQfFQ40lI",
        "is_featured": True,
        "category": "klassika"
      },
      {
        "title": "One Flew Over the Cuckoo's Nest",
        "description": "A rebel inmate challenges the oppressive system of a mental institution.",
        "year": 1975,
        "genre": "Drama",
        "director": "Miloš Forman",
        "actors": "Jack Nicholson, Louise Fletcher, Michael Berryman",
        "duration": "2h 13m",
        "rating": 8.7,
        "poster_url": "https://image.tmdb.org/t/p/w500/3.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=OXrcDonY-B8",
        "is_featured": True,
        "category": "klassika"
      },
      {
        "title": "Apocalypse Now",
        "description": "A soldier journeys through Vietnam to assassinate a rogue colonel.",
        "year": 1979,
        "genre": "Drama, War",
        "director": "Francis Ford Coppola",
        "actors": "Martin Sheen, Marlon Brando, Robert Duvall",
        "duration": "2h 27m",
        "rating": 8.4,
        "poster_url": "https://image.tmdb.org/t/p/w500/4.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=9l-VBly9Nkk",
        "is_featured": True,
        "category": "klassika"
      },
      {
        "title": "Dr. Strangelove",
        "description": "A mad general triggers a nuclear crisis, satirizing Cold War fears.",
        "year": 1964,
        "genre": "Comedy, War",
        "director": "Stanley Kubrick",
        "actors": "Peter Sellers, George C. Scott, Sterling Hayden",
        "duration": "1h 35m",
        "rating": 8.4,
        "poster_url": "https://image.tmdb.org/t/p/w500/7.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=IE9CmX15PYA",
        "is_featured": False,
        "category": "klassika"
      },
      {
        "title": "The Sound of Music",
        "description": "A governess brings joy to a family and escapes Nazi-occupied Austria.",
        "year": 1965,
        "genre": "Biography, Drama, Musical",
        "director": "Robert Wise",
        "actors": "Julie Andrews, Christopher Plummer, Eleanor Parker",
        "duration": "2h 52m",
        "rating": 8.1,
        "poster_url": "https://image.tmdb.org/t/p/w500/5.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=UY6uw3WpPzY",
        "is_featured": True,
        "category": "klassika"
      },
      {
        "title": "2001: A Space Odyssey",
        "description": "Humanity’s evolution is guided by mysterious monoliths in a cosmic journey.",
        "year": 1968,
        "genre": "Adventure, Sci-Fi",
        "director": "Stanley Kubrick",
        "actors": "Keir Dullea, Gary Lockwood, William Sylvester",
        "duration": "2h 29m",
        "rating": 8.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/v.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=oR_e9y-bka0",
        "is_featured": True,
        "category": "klassika"
      },
      {
        "title": "The Graduate",
        "description": "A young man is seduced by an older woman while grappling with his future.",
        "year": 1967,
        "genre": "Comedy, Drama, Romance",
        "director": "Mike Nichols",
        "actors": "Dustin Hoffman, Anne Bancroft, Katharine Ross",
        "duration": "1h 46m",
        "rating": 8.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/2.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=BF9Gh-a.png",
        "is_featured": False,
        "category": "klassika"
      },
      {
        "title": "Chinatown",
        "description": "A private detective uncovers corruption and family secrets in 1930s Los Angeles.",
        "year": 1974,
        "genre": "Drama, Mystery, Thriller",
        "director": "Roman Polanski",
        "actors": "Jack Nicholson, Faye Dunaway, John Huston",
        "duration": "2h 10m",
        "rating": 8.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/3.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=T37QkBc4IGY",
        "is_featured": True,
        "category": "klassika"
      },
      {
        "title": "Lawrence of Arabia",
        "description": "A British officer leads Arab tribes in a revolt during World War I.",
        "year": 1962,
        "genre": "Adventure, Biography, Drama",
        "director": "David Lean",
        "actors": "Peter O'Toole, Alec Guinness, Anthony Quinn",
        "duration": "3h 36m",
        "rating": 8.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/5.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=zmr1iAz152M",
        "is_featured": True,
        "category": "klassika"
      },
      {
        "title": "The Sting",
        "description": "Two con men team up to pull off a massive scam in 1930s Chicago.",
        "year": 1973,
        "genre": "Comedy, Crime, Drama",
        "director": "George Roy Hill",
        "actors": "Paul Newman, Robert Redford, Robert Shaw",
        "duration": "2h 9m",
        "rating": 8.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/3.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=LN2hBOIXhBs",
        "is_featured": False,
        "category": "klassika"
      },
      {
        "title": "Seven Samurai",
        "description": "A village hires seven warriors to protect them from bandits in feudal Japan.",
        "year": 1954,
        "genre": "Action, Adventure, Drama",
        "director": "Akira Kurosawa",
        "actors": "Toshiro Mifune, Takashi Shimura, Keiko Tsushima",
        "duration": "3h 27m",
        "rating": 8.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/8.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=wJ1TOratCTo",
        "is_featured": True,
        "category": "klassika"
      },
      {
        "title": "Die Hard",
        "description": "A New York cop takes on terrorists holding a skyscraper hostage.",
        "year": 1988,
        "genre": "Action, Thriller",
        "director": "John McTiernan",
        "actors": "Bruce Willis, Alan Rickman, Bonnie Bedelia",
        "duration": "2h 12m",
        "rating": 8.2,
        "poster_url": "https://image.tmdb.org/t/p/w500/y.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=jaJuwL0Mlh0",
        "is_featured": True,
        "category": "jangari"
      },
      {
        "title": "The Dark Knight",
        "description": "Batman faces the Joker, a chaotic criminal threatening Gotham’s order.",
        "year": 2008,
        "genre": "Action, Crime, Drama",
        "director": "Christopher Nolan",
        "actors": "Christian Bale, Heath Ledger, Aaron Eckhart",
        "duration": "2h 32m",
        "rating": 9.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/q.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=EXeTwQWrcwY",
        "is_featured": True,
        "category": "jangari"
      },
      {
        "title": "Mad Max: Fury Road",
        "description": "A warrior helps women escape a tyrant in a post-apocalyptic wasteland.",
        "year": 2015,
        "genre": "Action, Sci-Fi",
        "director": "George Miller",
        "actors": "Tom Hardy, Charlize Theron, Nicholas Hoult",
        "duration": "2h 0m",
        "rating": 8.1,
        "poster_url": "https://image.tmdb.org/t/p/w500/8.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=hEJnMQG9ev8",
        "is_featured": True,
        "category": "jangari"
      },
      {
        "title": "Gladiator",
        "description": "A betrayed Roman general seeks vengeance against a corrupt emperor.",
        "year": 2000,
        "genre": "Action, Adventure, Drama",
        "director": "Ridley Scott",
        "actors": "Russell Crowe, Joaquin Phoenix, Connie Nielsen",
        "duration": "2h 35m",
        "rating": 8.5,
        "poster_url": "https://image.tmdb.org/t/p/w500/e.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=owK1qxDselE",
        "is_featured": True,
        "category": "jangari"
      },
      {
        "title": "Terminator 2: Judgment Day",
        "description": "A cyborg protects a boy from a more advanced terminator sent to kill him.",
        "year": 1991,
        "genre": "Action, Sci-Fi",
        "director": "James Cameron",
        "actors": "Arnold Schwarzenegger, Linda Hamilton, Edward Furlong",
        "duration": "2h 17m",
        "rating": 8.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/2.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=lw-7wwPPkC0",
        "is_featured": True,
        "category": "jangari"
      },
      {
        "title": "John Wick",
        "description": "A retired hitman seeks revenge after thugs kill his dog and steal his car.",
        "year": 2014,
        "genre": "Action, Crime, Thriller",
        "director": "Chad Stahelski",
        "actors": "Keanu Reeves, Michael Nyqvist, Alfie Allen",
        "duration": "1h 41m",
        "rating": 7.4,
        "poster_url": "https://image.tmdb.org/t/p/w500/f.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=C0BMxG60m-o",
        "is_featured": True,
        "category": "jangari"
      },
      {
        "title": "The Bourne Identity",
        "description": "An amnesiac assassin evades his former employers while uncovering his past.",
        "year": 2002,
        "genre": "Action, Mystery, Thriller",
        "director": "Doug Liman",
        "actors": "Matt Damon, Franka Potente, Chris Cooper",
        "duration": "1h 59m",
        "rating": 7.9,
        "poster_url": "https://image.tmdb.org/t/p/w500/a.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=FpKaB2dvFL4",
        "is_featured": True,
        "category": "jangari"
      },
      {
        "title": "Raiders of the Lost Ark",
        "description": "An archaeologist races Nazis to find a powerful ancient artifact.",
        "year": 1981,
        "genre": "Action, Adventure",
        "director": "Steven Spielberg",
        "actors": "Harrison Ford, Karen Allen, Paul Freeman",
        "duration": "1h 55m",
        "rating": 8.4,
        "poster_url": "https://image.tmdb.org/t/p/w500/c.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=XkkzKHCeZ84",
        "is_featured": True,
        "category": "jangari"
      },
      {
        "title": "Inception",
        "description": "A thief enters dreams to steal secrets, tasked with planting an idea in a CEO’s mind.",
        "year": 2010,
        "genre": "Action, Adventure, Sci-Fi",
        "director": "Christopher Nolan",
        "actors": "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
        "duration": "2h 28m",
        "rating": 8.8,
        "poster_url": "https://image.tmdb.org/t/p/w500/qmDpIHrmpJINaRKAfWQfftjCdyi.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=YoHD9XEInc0",
        "is_featured": True,
        "category": "jangari"
      },
      {
        "title": "The Matrix",
        "description": "A hacker discovers reality is a simulation and joins a rebellion against machines.",
        "year": 1999,
        "genre": "Action, Sci-Fi",
        "director": "Lana Wachowski, Lilly Wachowski",
        "actors": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
        "duration": "2h 16m",
        "rating": 8.7,
        "poster_url": "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5Z.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=m8e-8oLKvP8",
        "is_featured": True,
        "category": "jangari"
      },
      {
        "title": "Saving Private Ryan",
        "description": "A squad searches for a paratrooper in WWII after his brothers die in combat.",
        "year": 1998,
        "genre": "Action, Drama, War",
        "director": "Steven Spielberg",
        "actors": "Tom Hanks, Matt Damon, Tom Sizemore",
        "duration": "2h 49m",
        "rating": 8.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/1.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=zwhP5b4tD6g",
        "is_featured": True,
        "category": "jangari"
      },
      {
        "title": "Lethal Weapon",
        "description": "A veteran cop and his volatile partner take on a drug-smuggling ring.",
        "year": 1987,
        "genre": "Action, Crime, Thriller",
        "director": "Richard Donner",
        "actors": "Mel Gibson, Danny Glover, Gary Busey",
        "duration": "1h 49m",
        "rating": 7.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/2.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=bSxqZ3nEO5A",
        "is_featured": False,
        "category": "jangari"
      },
      {
        "title": "Speed",
        "description": "A cop must stop a bus rigged to explode if it slows below 50 mph.",
        "year": 1994,
        "genre": "Action, Adventure, Thriller",
        "director": "Jan de Bont",
        "actors": "Keanu Reeves, Dennis Hopper, Sandra Bullock",
        "duration": "1h 56m",
        "rating": 7.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/3.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=FkcthC3n4pY",
        "is_featured": False,
        "category": "jangari"
      },
      {
        "title": "True Lies",
        "description": "A secret agent balances his spy life with family while stopping a terrorist.",
        "year": 1994,
        "genre": "Action, Comedy, Thriller",
        "director": "James Cameron",
        "actors": "Arnold Schwarzenegger, Jamie Lee Curtis, Tom Arnold",
        "duration": "2h 21m",
        "rating": 7.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/4.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=3b726feA8Uk",
        "is_featured": False,
        "category": "jangari"
      },
      {
        "title": "Heat",
        "description": "A master thief and a dedicated cop face off in a high-stakes cat-and-mouse game.",
        "year": 1995,
        "genre": "Action, Crime, Drama",
        "director": "Michael Mann",
        "actors": "Al Pacino, Robert De Niro, Val Kilmer",
        "duration": "2h 50m",
        "rating": 8.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/5.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=2GfBkC3qs28",
        "is_featured": True,
        "category": "jangari"
      },
      {
        "title": "Point Break",
        "description": "An FBI agent infiltrates a group of thrill-seeking bank robbers.",
        "year": 1991,
        "genre": "Action, Crime, Thriller",
        "director": "Kathryn Bigelow",
        "actors": "Patrick Swayze, Keanu Reeves, Gary Busey",
        "duration": "2h 2m",
        "rating": 7.3,
        "poster_url": "https://image.tmdb.org/t/p/w500/6.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=ncvFaGrs5c0",
        "is_featured": False,
        "category": "jangari"
      },
      {
        "title": "The Expendables",
        "description": "A team of mercenaries takes on a dangerous mission to overthrow a dictator.",
        "year": 2010,
        "genre": "Action, Adventure, Thriller",
        "director": "Sylvester Stallone",
        "actors": "Sylvester Stallone, Jason Statham, Jet Li",
        "duration": "1h 43m",
        "rating": 6.4,
        "poster_url": "https://image.tmdb.org/t/p/w500/7.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=CiTboN4.jpg",
        "is_featured": False,
        "category": "jangari"
      },
      {
        "title": "Casino Royale",
        "description": "James Bond’s first mission as 007 pits him against a terrorist financier.",
        "year": 2006,
        "genre": "Action, Adventure, Thriller",
        "director": "Martin Campbell",
        "actors": "Daniel Craig, Eva Green, Judi Dench",
        "duration": "2h 24m",
        "rating": 8.0,
        "poster_url": "https://image.tmdb.org/t/p/w500/8.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=36mnx8dBbGE",
        "is_featured": True,
        "category": "jangari"
      },
      {
        "title": "Skyfall",
        "description": "James Bond protects MI6 from a cyber-terrorist with a personal vendetta.",
        "year": 2012,
        "genre": "Action, Adventure, Thriller",
        "director": "Sam Mendes",
        "actors": "Daniel Craig, Javier Bardem, Naomie Harris",
        "duration": "2h 23m",
        "rating": 7.8,
        "poster_url": "https://image.tmdb.org/t/p/w500/9.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=6kw1UVovByw",
        "is_featured": True,
        "category": "jangari"
      },
      {
        "title": "Fury",
        "description": "A tank crew faces impossible odds in the final days of WWII.",
        "year": 2014,
        "genre": "Action, Drama, War",
        "director": "David Ayer",
        "actors": "Brad Pitt, Shia LaBeouf, Logan Lerman",
        "duration": "2h 14m",
        "rating": 7.6,
        "poster_url": "https://image.tmdb.org/t/p/w500/1.jpg",
        "trailer_url": "https://www.youtube.com/watch?v=-OGvZoIrXpg",
        "is_featured": False,
        "category": "jangari"
      }
    ]     
        created_count = 0
        for movie_data in real_movies_data:
            movie, created = Movie.objects.get_or_create(
                title=movie_data['title'],
                defaults=movie_data
            )
            if created:
                created_count += 1
                self.stdout.write(
                    self.style.SUCCESS(f'✓ "{movie.title}" qoʻshildi')
                )
            else:
                self.stdout.write(
                    self.style.WARNING(f'- "{movie.title}" allaqachon mavjud')
                )

        self.stdout.write(
            self.style.SUCCESS(f'\n✓ Jami {created_count} ta yangi film qoʻshildi!')
        )
